@startuml

title -Proyecto-

skinparam linetype ortho

interface ElementoMenu {

    +getPrecio():number

    +getNombre():String



}

abstract class Pedido{

    -numeroPedido: int

    -nombreCliente: String

    -fecha: Date

    -estado: EstadoPedido

    -item: List<Item>



    +agregarItem(item:Item)

    +quitarItem(item:Item)

    +registrarPedido()

    +deshacerModificacion()

    +confirmarPedido()

    +puedeFacturable()

    +totalPedido()

}

class PedidoSalon{

    -numeroMesa: int

    -mozo: String

}

class PedidoRetirar{

    -horarioRetiro: Date

}

class PedidoEnvioPropio{

    -direccion: String

    -costoEnvio: int



}



class Item{

    -estado:EstadioItem



    +avanzarEstado()

    +esModificable()



}

class Producto{

    -nombre: String

    -precioDeVenta:number



    +getPrecio(): number

    +getNombre(): String



   

}

class Combo {

    -nombre: String

    -productos: List<Producto>

    -precioEspecial: number

    -calcularTotal(): number

    +getPrecio(): number

    +getNombre(): String

}

class Categoria{



}

class Estacion{

    -nombre: String

    -items:List<Item>



    +agregarItem(item:Item)

    +avanzarItem(item:Item)



}



class Menu{

    -categorias: List<Categoria>

    -combos: List<Combo>

    -productos: List<Producto>



}

'preguntas si conviene  tenerlo como clase abstracta y que hereden los distintos medios de pagos'

class MedioDePago{



}

enum EstadoPedido {

    EN_CONSTRUCCION,

    CONFIRMADO,

    LISTO,

    FACTURADO

}

enum EstadioItem{

    PENDIENTE,

    EN_PREPARACION,

    LISTO

}

Pedido <|-l- PedidoSalon

Pedido <|-- PedidoRetirar

Pedido <|-r- PedidoEnvioPropio

Menu o-- Categoria

Menu o-l- Producto

Menu o-r- Combo

ElementoMenu <|.l. Producto

ElementoMenu <|.l. Combo

Estacion -- Item

'Item --> ElementoMenu

@enduml